name: Static analysis

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3.4'
          coverage: none
          extensions: mbstring, intl

      - name: Download dependencies
        run: composer install --no-interaction --no-progress

      - name: Execute Psalm
        run: vendor/bin/psalm --no-progress --output-format=github --shepherd
